version: "3"
services:
  roach:
    image: cockroachdb/cockroach:v19.1.4
    ports:
      - 12080:8080
      - 26257:26257
    volumes:
      - ${PWD}/data:/cockroach/data
    command: start --insecure --listen-addr=0.0.0.0 --store data
  pgweb:
    image: sosedoff/pgweb
    ports:
      - 12081:8081
    environment:
      - DATABASE_URL=postgres://root:@roach:26257/postgres?sslmode=disable
    depends_on:
      - roach
