version: "3"
services:
  roach1:
    image: cockroachdb/cockroach:v19.1.4
    restart: always
    ports:
      - 8082:8080
      - 26257:26257
    volumes:
      - ${PWD}/data:/cockroach/cockroach-data
    command: start --insecure
    networks:
      - roachnet
  roach2:
    image: cockroachdb/cockroach:v19.1.4
    restart: always
    volumes:
      - ${PWD}/data2:/cockroach/cockroach-data
    command: start --insecure --join=roach1
    depends_on:
      - roach1
    networks:
      - roachnet
  roach3:
    image: cockroachdb/cockroach:v19.1.4
    restart: always
    volumes:
      - ${PWD}/data3:/cockroach/cockroach-data
    command: start --insecure --join=roach1
    depends_on:
      - roach1
    networks:
      - roachnet
  pgweb:
    image: sosedoff/pgweb
    restart: always
    ports:
      - 8081:8081
    environment:
      - DATABASE_URL=postgres://root:@roach1:26257/postgres?sslmode=disable
    depends_on:
      - roach1
    networks:
      - roachnet
networks:
  roachnet:
    driver: bridge
